import {describe,expect,it} from "vitest";
import {ScoringService} from "./scoring-service";
import {RoomActionService,RoomPermissionService,RoomRewardService} from "./room-services";
import {events,rules,users,rooms,slots} from "../../dev/seed";
import type {RoomActionEntitlement,RoomTrap} from "../models/rooms";
describe("ScoringService",()=>{it("scores completed, missed, challenge and unmatched events",()=>{const e=[events[0],{...events[0],id:"2",actionType:"action_missed" as const},{...events[0],id:"3",actionType:"challenge_completed" as const},{...events[0],id:"4",actionType:"challenge_created" as const}];expect(new ScoringService().score(e,rules).map(x=>x.points)).toEqual([2,-1,3,0])});it("uses changed current rules for previews",()=>expect(new ScoringService().score(events,[{...rules[0],points:9}])[0].points).toBe(9))});
it("selects the highest matching rule version deterministically",()=>expect(new ScoringService().score(events,[rules[0],{...rules[0],id:"new",version:2,points:7}])[0]).toMatchObject({points:7,ruleVersion:2}));
describe("RoomRewardService",()=>{const service=new RoomRewardService();it("finds winner and grants both token types",()=>expect(service.rewards({[users.william]:5,[users.sister]:2},"2026-06-29").map(r=>r.type)).toEqual(["mischief","defense"]));it("grants defense on ties",()=>expect(service.rewards({a:2,b:2},"d").every(r=>r.type==="defense")).toBe(true));it("prevents duplicates",()=>expect(service.rewards({a:2,b:1},"d",new Set(["a:d:mischief"]))).toHaveLength(1))});
describe("Room permissions/actions",()=>{const entitlement:RoomActionEntitlement={id:"e",challengeGroupId:"g",userId:users.william,targetUserId:users.sister,entitlementType:"mischief",sourceDate:"2026-06-29",createdAt:new Date().toISOString()};it("allows valid raid",()=>expect(new RoomPermissionService().canRaid(users.william,rooms[1],entitlement)).toBe(true));it("blocks protected slot",()=>expect(new RoomActionService().resolve(slots[0])).toBe("blocked"));it("triggers glue trap",()=>expect(new RoomActionService().resolve(slots[1],{status:"active",trapType:"glue_trap"} as RoomTrap)).toBe("trap_triggered"));it("reflects mirror trap",()=>expect(new RoomActionService().resolve(slots[1],{status:"active",trapType:"mirror_trap"} as RoomTrap)).toBe("reflected"));it("rejects expired entitlement",()=>expect(new RoomPermissionService().entitlementValid({...entitlement,expiresAt:"2020-01-01"})).toBe(false))});
