export const uiContent = {
  navigation: [
    { to: "/", icon: "☑", label: "Today" },
    { to: "/house", icon: "⌂", label: "House" },
    { to: "/rewards", icon: "☆", label: "Rewards" },
  ],
  home: {
    title: "Today", subtitle: "Quick tasks, sibling proof, daily tokens",
    youLabel: "You", siblingLabel: "Sibling", versusLabel: "vs", scoreScope: "Logged points",
    progressTitle: "One small win at a time", tasksTitle: "Your tasks", addLabel: "+ Add",
    emptyTasks: "Start with one small task. What would you like to do?",
    taskStorageHint: "Task list stays on this device. Completed actions go to your shared feed.",
    completionHint: "Completed logs are permanent evidence. Checking a task again cannot earn more points.",
    taskPlaceholder: "Add task", saveTaskLabel: "Save task", cancelTaskLabel: "Cancel task",
    completeTaskLabel: "Complete", completedTaskLabel: "Completed", starTaskLabel: "Star",
    retryTaskLabel: "Retry completion", retryLabel: "Retry", savingLabel: "Saving…",
    progress: (done:number,total:number)=>`${done} of ${total} done`,
    siblingActivity: "Sibling activity", emptyActivity: "No shared activity from your sibling yet.",
    houseTitle: "House preview", houseReady: (name:string)=>`${name} is ready for visitors.`,
    houseEmpty: "Your room will appear here when ready.", houseLink: "Open House",
    mischiefLabel: "Mischief", defenseLabel: "Defense",
    finalizeTitle: "Finalize day?", finalizeBody: "Records the eligible day’s scores and rewards once. Unfinished tasks stay on your list.",
    confirmLabel: "Confirm", cancelLabel: "Cancel", finalizeLabel: "Finalize Day →",
    finalizingLabel: "Finalizing…", finalizedLabel: "Finalized ✓", tieLabel: "Tie day",
    finalizedTitle: "Day finalized", finalizedMessage: "Day recorded. Available tokens refreshed.",
    finalizeError: "Unable to finalize day. Please retry.",
    feedLink: "Full feed", resultsLink: "Weekly results", rulesLink: "Rules",
    pointsLabel: "points", todayTitle: "Today",
    actions: [
      { to: "/log", label: "Quick Log" },
      { to: "/feed", label: "Send Challenge" },
      { to: "/results", label: "Weekly Results" },
    ],
    today: ["🏋️ Workout logged", "🌙 Sleep pending", "👥 2 challenges"],
  },
  quickLog: {
    title: "Quick Log", subtitle: "Record today’s progress",
    positiveLabel: "＋ Points", penaltyLabel: "− Penalty",
    notePlaceholder: "Optional note", saveLabel: "Save Log",
    savingLabel: "Saving…", loadingLabel: "Loading…", savedLabel: "Log saved ✓",
    anotherLabel: "Log another action", retryLabel: "Retry same log", saveError: "Unable to save. Retry this log.",
    pendingHint: "This log is kept on this device until saved. Retry sends the same log once.",
    options: [
      { label: "Workout", icon: "🏋️" }, { label: "Meal", icon: "🍴" },
      { label: "Sleep", icon: "🌙" }, { label: "Work", icon: "💼" },
      { label: "Custom", icon: "⭐" },
    ],
    completedDescription: "Completed or stayed on plan", missedDescription: "Missed today",
  },
  feed: {
    title: "Challenge Feed", subtitle: "Playful accountability updates",
    sendLabel: "Send Challenge", filterLabel: "Filter",
    roomLabel: "Room activity", roomTitle: "Sister left a tiny flag",
  },
  results: {
    title: "Weekly Results", subtitle: "How the race is going",
    leaderLabel: "Current Leader", leadSummary: "You’re ahead by 4 points!",
    chartTitle: "Daily points comparison", finalizeLabel: "Finalize Day",
    finalizeHint: "Finalization is atomic in Supabase and can only succeed once per local day.",
    dayLabels: ["M", "T", "W", "T", "F", "S", "S"],
  },
  rules: {
    title: "Point Rules", subtitle: "Keep the race fair and clear",
    historyTitle: "Historical scoring",
    historyBody: "Finalized days keep the exact rule IDs and versions used. Editing a rule never rewrites history.",
  },
  rooms: {
    title: "The Showdown House", subtitle: "One shared house, two cozy rooms",
    overviewTitle: "Airship house",
    overviewBody: "Each sibling keeps a room here. Earn tokens today, then visit with harmless mischief or set a defense.",
    mischiefToken: "⚡ 1 Mischief", defenseToken: "🛡 1 Defense",
    descriptions: ["Your cozy workshop", "A breezy room above the clouds"],
    ownActions: ["Enter My Room", "Set Traps"], otherActions: ["Visit Room", "Mischief Visit"],
    viewSubtitle: "Tap a slot to see its status", recentTitle: "Recent changes",
    recentBody: "Tiny flag added · Lighting warmed · Poster moved",
    decorateLabel: "Decorate", raidLabel: "Enter Raid Mode", trapsLabel: "Set Traps",
  },
  raid: {
    title: "Raid Mode", subtitle: "One token, one harmless change",
    token: "1 Mischief Token", chooseTitle: "Choose an action",
    actions: ["Add confetti", "Place funny poster", "Add tiny flag", "Change lighting"],
    protectedTitle: "Protected slots", protectedBody: "Wall and bed are locked. A trap may be active.",
    confirmPrefix: "Confirm",
  },
  traps: {
    title: "Trap Setup", subtitle: "Defend without spoiling the fun",
    token: "1 Defense Token", protectedTitle: "Protected slots · 2/2",
    protectedBody: "Wall 🔒 · Bed 🔒", saveLabel: "Set Trap",
    types: ["Alarm bell", "Glue trap", "Decoy object", "Mirror trap", "Lock trap"],
  },
  result: {
    title: "Prank Applied!", subtitle: "The room survived the mischief",
    heading: "Tiny flag planted",
    summary: "Feed summary: William added a tiny flag to Sister’s shelf.",
    technicalResult: "RoomAction result: applied",
    roomLabel: "Return to house", feedLabel: "View feed",
  },
  rewards: {
    title: "Rewards", subtitle: "Cosmetics earned from daily effort",
    currentLookTitle: "Current look",
    currentLookBody: "Steampunk explorer · chrome goggles · crimson scarf",
    comingSoonTitle: "Shop coming soon",
    comingSoonBody: "MVP keeps rewards lightweight. Coins and inventory can grow after the daily loop works.",
    items: [
      {name:"Chrome Goggles",state:"Equipped",icon:"🥽"},
      {name:"Crimson Scarf",state:"Equipped",icon:"🧣"},
      {name:"Tiny Flag",state:"Unlocked",icon:"🚩"},
      {name:"Squeaky Alarm",state:"Locked · 8 coins",icon:"⏰"},
      {name:"Confetti Floor",state:"Unlocked",icon:"🎊"},
      {name:"Star Poster",state:"Locked · 5 coins",icon:"⭐"},
    ],
  },
} as const;
