import {useState} from "react";import {Link,useNavigate,useParams} from "react-router-dom";
import {Button,Card,PageHeader,StatusChip} from "../../components/ui";
import {VisualAsset} from "../../components/VisualAsset";
import {uiContent} from "../../config/ui-content";
import {rooms,slots,users} from "../../dev/seed";

export function RoomsHomePage(){const copy=uiContent.rooms;return <><PageHeader title={copy.title} subtitle={copy.subtitle}/><div className="token-row"><StatusChip tone="orange">{copy.mischiefToken}</StatusChip><StatusChip tone="blue">{copy.defenseToken}</StatusChip></div>{rooms.map((room,index)=>{const own=index===0;const labels=own?copy.ownActions:copy.otherActions;return <Card className="room-card" key={room.id}><div className={`room-preview theme-${room.theme}`}><VisualAsset asset={own?"roomWorkshop":"roomSky"}/><span>🔒 🔒</span></div><h2>{room.name}</h2><p>{copy.descriptions[index]}</p><div className="split"><Link className="button-link" to={`/rooms/${room.id}`}>{labels[0]}</Link><Link to={own?"/rooms/room-w/traps":"/rooms/room-s/raid"}>{labels[1]}</Link></div></Card>})}</>}
export function RoomViewPage(){const {roomId}=useParams();const copy=uiContent.rooms;const room=rooms.find(item=>item.id===roomId)??rooms[0];return <><PageHeader title={room.name} subtitle={copy.viewSubtitle}/><div className="room-canvas">{slots.slice(0,8).map(slot=><div className={slot.isProtected?"protected":""} key={slot.id}>{slot.slotKey}{slot.isProtected?<span aria-label="Protected">🔒</span>:null}</div>)}</div><Card><h2>{copy.recentTitle}</h2><p>{copy.recentBody}</p></Card><div className="split"><Button>{copy.decorateLabel}</Button>{room.ownerId!==users.william?<Link className="button-link" to={`/rooms/${room.id}/raid`}>{copy.raidLabel}</Link>:<Link to={`/rooms/${room.id}/traps`}>{copy.trapsLabel}</Link>}</div></>}
export function RaidPage(){const copy=uiContent.raid;const navigate=useNavigate();const [action,setAction]=useState<string>(copy.actions[0]);return <><PageHeader title={copy.title} subtitle={copy.subtitle}/><Card><StatusChip tone="orange">{copy.token}</StatusChip><h2>{copy.chooseTitle}</h2><div role="radiogroup" aria-label={copy.chooseTitle}>{copy.actions.map(item=><button type="button" role="radio" aria-checked={action===item} className={`choice ${action===item?"selected":""}`} onClick={()=>setAction(item)} key={item}>{item}</button>)}</div></Card><Card><h2>{copy.protectedTitle}</h2><p>{copy.protectedBody}</p></Card><Button onClick={()=>navigate("/room-action-result",{state:{action}})}>{copy.confirmPrefix} {action}</Button></>}
export function TrapSetupPage(){const copy=uiContent.traps;const [selected,setSelected]=useState<string>(copy.types[0]);return <><PageHeader title={copy.title} subtitle={copy.subtitle}/><StatusChip tone="blue">{copy.token}</StatusChip><Card><div role="radiogroup" aria-label="Trap type">{copy.types.map(type=><button type="button" role="radio" aria-checked={selected===type} onClick={()=>setSelected(type)} className={`choice ${selected===type?"selected":""}`} key={type}>{type}</button>)}</div></Card><Card><h2>{copy.protectedTitle}</h2><p>{copy.protectedBody}</p></Card><Button>{copy.saveLabel}</Button></>}
export function RoomActionResultPage(){const copy=uiContent.result;return <><PageHeader title={copy.title} subtitle={copy.subtitle}/><Card className="result"><VisualAsset asset="resultCelebration"/><h2>{copy.heading}</h2><p>{copy.summary}</p><code>{copy.technicalResult}</code></Card><div className="split"><Link className="button-link" to="/rooms/room-s">{copy.roomLabel}</Link><Link to="/feed">{copy.feedLabel}</Link></div></>}
